// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20200511133817_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Model.Speler", b =>
                {
                    b.Property<int>("SpelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TeamStamnummer")
                        .HasColumnType("int");

                    b.Property<string>("naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rugnummer")
                        .HasColumnType("int");

                    b.Property<double>("value")
                        .HasColumnType("float");

                    b.HasKey("SpelerId");

                    b.HasIndex("TeamStamnummer");

                    b.ToTable("Spelers");
                });

            modelBuilder.Entity("DataLayer.Model.Team", b =>
                {
                    b.Property<int>("Stamnummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bijnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trainer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stamnummer");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DataLayer.Model.Transfer", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NieuweClubStamnummer")
                        .HasColumnType("int");

                    b.Property<int?>("OudeClubStamnummer")
                        .HasColumnType("int");

                    b.Property<double>("Prijs")
                        .HasColumnType("float");

                    b.Property<int?>("SpelerId")
                        .HasColumnType("int");

                    b.HasKey("TransferId");

                    b.HasIndex("NieuweClubStamnummer");

                    b.HasIndex("OudeClubStamnummer");

                    b.HasIndex("SpelerId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("DataLayer.Model.Speler", b =>
                {
                    b.HasOne("DataLayer.Model.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamStamnummer");
                });

            modelBuilder.Entity("DataLayer.Model.Transfer", b =>
                {
                    b.HasOne("DataLayer.Model.Team", "NieuweClub")
                        .WithMany()
                        .HasForeignKey("NieuweClubStamnummer");

                    b.HasOne("DataLayer.Model.Team", "OudeClub")
                        .WithMany()
                        .HasForeignKey("OudeClubStamnummer");

                    b.HasOne("DataLayer.Model.Speler", "Speler")
                        .WithMany()
                        .HasForeignKey("SpelerId");
                });
#pragma warning restore 612, 618
        }
    }
}
